# Notebook that retrieves API data related to tracks

## Imports

In [8]:
import base64
import pandas as pd
import requests
from time import sleep

from typing import List, Any

## Methods

In [9]:
# Split a list into chunks of specified size
def chunk_list(data: List[Any], chunk_size: int = 0, max_chunk: int = None):
    if chunk_size > 0:
        size = chunk_size
        if max_chunk is not None:
            size = min(chunk_size, max_chunk)
    elif max_chunk is not None and max_chunk > 0:
        size = max_chunk
    else:
        size = 100  # default chunk size

    for i in range(0, len(data), size):
        yield data[i:i + size]

## Reading dataset

In [27]:
df_treated = pd.read_csv("final_df.csv")

## ReccoBeats APIs - [Get multiple track](https://reccobeats.com/docs/apis/get-tracks) and [Get multiple audio features](https://reccobeats.com/docs/apis/get-audio-features)

In [28]:
unique_track_id_list = df_treated["track_id"].unique()

headers = {
  'Accept': 'application/json'
}

audio_features_dataframes = []
multiple_track_dataframes = []

for chunk in chunk_list(unique_track_id_list, 40):
    # print(chunk)
    print(f"Len: {len(chunk)}")

    url_audio_features = "https://api.reccobeats.com/v1/audio-features?ids="
    url_multiple_track = "https://api.reccobeats.com/v1/track?ids="

    track_ids_str = ",".join([track_id for track_id in chunk])

    url_audio_features += track_ids_str
    url_multiple_track += track_ids_str

    response_audio_features = requests.get(url=url_audio_features, headers=headers)
    response_multiple_track = requests.get(url=url_multiple_track, headers=headers)
    
    audio_features_dataframes.append(pd.json_normalize(response_audio_features.json(), record_path="content"))
    multiple_track_dataframes.append(pd.json_normalize(response_multiple_track.json(), record_path="content"))

df_audio_features = pd.concat(audio_features_dataframes, ignore_index=True)
df_multiple_track = pd.concat(multiple_track_dataframes, ignore_index=True)

df_audio_features["track_id"] = df_audio_features["href"].str.rpartition("/")[2]
df_multiple_track["track_id"] = df_multiple_track["href"].str.rpartition("/")[2]

Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 40
Len: 30

## Checking results

In [29]:
display(df_audio_features.head(5))
display(df_multiple_track.head(5))

,id,href,isrc,acousticness,danceability,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,valence,track_id
0,666543a0-04fb-40c1-845b-668beefa1a88,https://open.spotify.com/track/6RUKPb4LETWmmr3...,USQX91700278,0.04980,0.617,0.635,0.000014,11.0,0.1640,-6.769,0.0,0.0317,103.019,0.446,6RUKPb4LETWmmr3iAEQktW
1,96758562-28d9-43de-9249-79a49b8f4994,https://open.spotify.com/track/4tHqQMWSqmL6YjX...,USSM19912814,0.99400,0.418,0.106,0.029200,8.0,0.1790,-22.507,0.0,0.0448,46.718,0.800,4tHqQMWSqmL6YjXwsqthDI
2,80dd06dd-8508-4ac0-b023-d21c40fe2c5a,https://open.spotify.com/track/0HmONWWIU1FXkwW...,NOG841549020,0.00073,0.750,0.617,0.318000,6.0,0.1050,-6.725,1.0,0.0318,89.968,0.108,0HmONWWIU1FXkwWLDpqrjl
3,59935bea-5e0a-4c00-8269-b01baa8c1992,https://open.spotify.com/track/1dNIEtp7AY3oDAK...,USQX91700278,0.03060,0.607,0.649,0.000025,11.0,0.1740,-6.695,0.0,0.0362,102.996,0.505,1dNIEtp7AY3oDAKCGg2XkH
4,ca0b1c69-be5d-4754-a490-efba6d4911fc,https://open.spotify.com/track/0u8aj0c4IxeVSLT...,BRSME1700003,0.37400,0.854,0.682,0.000000,9.0,0.0697,-5.818,0.0,0.0690,98.023,0.887,0u8aj0c4IxeVSLTUuuq9V5

,id,trackTitle,artists,durationMs,isrc,ean,upc,href,availableCountries,popularity,track_id
0,666543a0-04fb-40c1-845b-668beefa1a88,Something Just Like This,[{'id': 'e074334e-20b0-4f9e-a212-5b5632a4e935'...,247160,USQX91700278,None,None,https://open.spotify.com/track/6RUKPb4LETWmmr3...,"AR,AU,AT,BE,BO,BR,BG,CA,CL,CO,CR,CY,CZ,DK,DO,D...",86,6RUKPb4LETWmmr3iAEQktW
1,96758562-28d9-43de-9249-79a49b8f4994,Carol of the Bells,[{'id': '640564f3-58c4-4b17-bd41-e228e77bf7c1'...,85266,USSM19912814,None,None,https://open.spotify.com/track/4tHqQMWSqmL6YjX...,"AR,AU,AT,BE,BO,BR,BG,CA,CL,CO,CR,CY,CZ,DK,DO,D...",80,4tHqQMWSqmL6YjXwsqthDI
2,80dd06dd-8508-4ac0-b023-d21c40fe2c5a,Faded - Instrumental,[{'id': '0a5d81f9-b98b-46b7-84e7-7b19f340cf61'...,214013,NOG841549020,None,None,https://open.spotify.com/track/0HmONWWIU1FXkwW...,"AR,AU,AT,BE,BO,BR,BG,CA,CL,CO,CR,CY,CZ,DK,DO,D...",45,0HmONWWIU1FXkwWLDpqrjl
3,59935bea-5e0a-4c00-8269-b01baa8c1992,Something Just Like This,[{'id': 'e074334e-20b0-4f9e-a212-5b5632a4e935'...,247626,USQX91700278,None,None,https://open.spotify.com/track/1dNIEtp7AY3oDAK...,"AR,AU,AT,BE,BO,BR,BG,CA,CL,CO,CR,CY,CZ,DK,DO,D...",69,1dNIEtp7AY3oDAKCGg2XkH
4,ca0b1c69-be5d-4754-a490-efba6d4911fc,Você Partiu Meu Coração (feat. Anitta & Wesley...,[{'id': 'dd7180b0-f357-4ef8-9ea4-9861c91f4001'...,179000,BRSME1700003,None,None,https://open.spotify.com/track/0u8aj0c4IxeVSLT...,"AR,AU,AT,BE,BO,BR,BG,CA,CL,CO,CR,CY,CZ,DK,DO,D...",54,0u8aj0c4IxeVSLTUuuq9V5

## Merging dataframes

In [34]:
df_final = df_treated.merge(
    df_audio_features[["track_id", "acousticness", "danceability", "energy", "instrumentalness", "key", "liveness", "loudness", "mode", "speechiness", "tempo", "valence"]], # campos a serem trazidos do df_audio_features
    on="track_id", # track_id tem que tar na lista de cima
    how="left"
)

df_final = df_final.merge(
    df_multiple_track[["track_id", "popularity"]], # campos a serem trazidos do df_multiple_track
    on="track_id", # track_id tem que tar na lista de cima
    how="left"
)

In [36]:
df_final.to_csv("final_df.csv")