# Imports

In [7]:
import pandas as pd

# Constants

In [ ]:
PATH_SPOTIFY = '../../data/2_processed/final_df.csv'
PATH_PROCESSED = '../../data/2_processed/processed.csv'

# Getting DF

In [ ]:
df = pd.read_csv(PATH_SPOTIFY)
df

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_album_name,spotify_track_uri,episode_name,episode_show_name,...,key,liveness,loudness,mode,speechiness,tempo,valence,popularity,duration_ms,percentage_played
0,2017-11-21T11:46:01Z,"iOS 9.3.5 (iPad2,5)",6826,BR,201.6.225.101,The Society,Injustice 2: Original Video Game Soundtrack,spotify:track:74ovIDtL0HzDazMENhR0yX,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-11-21T11:46:18Z,"iOS 9.3.5 (iPad2,5)",16648,BR,201.6.225.101,Injustice 2 Main Theme,Injustice 2: Original Video Game Soundtrack,spotify:track:0QKHV9dERThRvpdzQWy8qd,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-11-21T11:46:19Z,"iOS 9.3.5 (iPad2,5)",766,BR,201.6.225.101,Brainiac Takes Krypton,Injustice 2: Original Video Game Soundtrack,spotify:track:7urxa3s1BTWXmx2Eb9QWLp,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-11-21T11:48:59Z,"iOS 9.3.5 (iPad2,5)",15371,BR,201.6.225.101,Gotham Projection Room,Injustice 2: Original Video Game Soundtrack,spotify:track:6qNM4ljTc8PGO3hzjZj4sg,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-11-21T11:50:16Z,"iOS 9.3.5 (iPad2,5)",58653,BR,201.6.225.101,Waiting for Superman,Baptized (Deluxe Version),spotify:track:4AU7z13HYmPMetlWbq1mys,NaN,NaN,...,0.0,0.0662,-5.711,1.0,0.0269,105.987,0.383,56.0,266960.0,0.2197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45373,2026-01-29T22:47:59Z,android,288480,BR,2804:18:1922:2821:188f:50ea:6b13:92e3,Adeus,13 Lentes de um Final Feliz,spotify:track:0xj6zeRC0uKy9ZbqpjvZ3n,NaN,NaN,...,3.0,0.0985,-4.921,1.0,0.0375,124.964,0.346,46.0,288480.0,1.0000
45374,2026-01-29T22:51:12Z,android,196512,BR,2804:18:1922:2821:188f:50ea:6b13:92e3,Não sou mais um,Trashtalk,spotify:track:5Qnc7ANm0fpGFdbxEvNBhe,NaN,NaN,...,2.0,0.1100,-4.507,1.0,0.0710,119.966,0.238,31.0,196511.0,1.0000
45375,2026-01-29T22:54:35Z,android,205714,BR,2804:18:1922:2821:188f:50ea:6b13:92e3,Going Home,Validation Deluxe,spotify:track:6cHQ5HrvdREnsGhUYv5x3p,NaN,NaN,...,8.0,0.1010,-4.164,1.0,0.2820,140.047,0.766,39.0,205714.0,1.0000
45376,2026-01-29T22:58:30Z,android,237923,BR,2804:18:1922:2821:188f:50ea:6b13:92e3,Quinto Elemento,Quinto Elemento,spotify:track:6VVYaR90TI9S5IQXrk1NtC,NaN,NaN,...,5.0,0.1060,-8.639,0.0,0.0309,113.986,0.335,28.0,237923.0,1.0000
45377,2026-01-29T23:02:26Z,android,238545,BR,2804:18:1922:2821:188f:50ea:6b13:92e3,I'm in Love,Validation Deluxe,spotify:track:5NyFih9oWwudqYKh6SLUjc,NaN,NaN,...,11.0,0.1710,-6.333,0.0,0.0717,82.525,0.630,38.0,238545.0,1.0000

In [ ]:
# 3. Convert lookup series to Python sets, before creating boolean columns
playlist_uris = set(playlist['track_track_uri'].dropna())
library_uris = set(library['uri'].dropna())

final_df['in_playlist'] = final_df['spotify_track_uri'].isin(playlist_uris)
final_df['in_library'] = final_df['spotify_track_uri'].isin(library_uris)

# creating playlist_percentage

In [ ]:
#get total amount of playlist
playlist_amount = playlist['playlists_name'].nunique()

# 1. Get the counts of each value in df_2
counts = playlist['track_track_uri'].value_counts()

# 2. Map those counts to df_1
final_df['playlist_count'] = final_df['spotify_track_uri'].map(counts)

# 3. Fill NaNs with 0 (for values that didn't appear in df_2) and convert to integer
final_df['playlist_count'] = final_df['playlist_count'].fillna(0).astype(int)

final_df['percentage_playlists'] = final_df['playlist_count'] / playlist_amount

final_df

# Creating next_track column

In [ ]:
final_df['ts'] = pd.to_datetime(final_df['ts'])
final_df = final_df.sort_values('ts')
final_df['next_track'] = final_df['spotify_track_uri'].shift(-1)
final_df

### Adding percentage_listened column

In [ ]:
df_final['percentage_played'] = (df_final['ms_played'] / df_final['duration_ms']).round(4)

# Droping columns

In [9]:
columns_to_drop = ["ip_addr",
    "spotify_track_uri",
    "episode_name",
    "episode_show_name",
    "spotify_episode_uri",
    "audiobook_title",
    "audiobook_uri",
    "audiobook_chapter_uri",
    "audiobook_chapter_title",
    "offline_timestamp",
    "in_playlist",
    "lat_long",
    "track_id",
    "ms_played",
    "duration_ms",
    "Unnamed: 0",
    "platform"
    ]

for i in columns_to_drop:
    try:
        df = df.drop(columns=i)
    except:
        print(f"A coluna {i} não existe no df")
df.columns

A coluna Unnamed: 0 não existe no df

Index(['ts', 'conn_country', 'master_metadata_track_name',
       'master_metadata_album_album_name', 'reason_start', 'reason_end',
       'shuffle', 'skipped', 'offline', 'incognito_mode', 'artist_name',
       'segment', 'in_library', 'temperature', 'precipitation', 'acousticness',
       'danceability', 'energy', 'instrumentalness', 'key', 'liveness',
       'loudness', 'mode', 'speechiness', 'tempo', 'valence', 'popularity',
       'percentage_played'],
      dtype='object')

# Droping NAs

In [10]:
not_na_df = df.dropna(subset="popularity")
not_na_df

,ts,conn_country,master_metadata_track_name,master_metadata_album_album_name,reason_start,reason_end,shuffle,skipped,offline,incognito_mode,...,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,valence,popularity,percentage_played
4,2017-11-21T11:50:16Z,BR,Waiting for Superman,Baptized (Deluxe Version),clickrow,endplay,False,False,False,False,...,0.000000,0.0,0.0662,-5.711,1.0,0.0269,105.987,0.383,56.0,0.2197
5,2017-11-21T11:50:25Z,BR,Liga da Justiça,Liga da Justiça,clickrow,endplay,False,False,False,False,...,0.000000,7.0,0.3780,-4.806,1.0,0.1330,129.550,0.881,0.0,0.0375
6,2017-11-21T11:51:31Z,BR,Liga Da Justiça (Mulher Maravilha),Liga Da Justiça (Mulher Maravilha),clickrow,endplay,False,False,False,False,...,0.000000,2.0,0.5000,-10.209,1.0,0.0955,129.424,0.911,45.0,0.2999
7,2017-11-21T11:53:57Z,BR,Liga Da Justiça (Mulher Maravilha),Liga Da Justiça (Mulher Maravilha),clickrow,endplay,False,False,False,False,...,0.000000,2.0,0.5000,-10.209,1.0,0.0955,129.424,0.911,45.0,0.6652
8,2017-11-21T11:54:32Z,BR,Faded,Faded,clickrow,endplay,False,False,False,False,...,0.000003,6.0,0.1110,-5.097,1.0,0.0306,90.011,0.166,69.0,0.1651
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45373,2026-01-29T22:47:59Z,BR,Adeus,13 Lentes de um Final Feliz,trackdone,trackdone,True,False,False,False,...,0.000006,3.0,0.0985,-4.921,1.0,0.0375,124.964,0.346,46.0,1.0000
45374,2026-01-29T22:51:12Z,BR,Não sou mais um,Trashtalk,trackdone,trackdone,True,False,False,False,...,0.000024,2.0,0.1100,-4.507,1.0,0.0710,119.966,0.238,31.0,1.0000
45375,2026-01-29T22:54:35Z,BR,Going Home,Validation Deluxe,trackdone,trackdone,True,False,False,False,...,0.000000,8.0,0.1010,-4.164,1.0,0.2820,140.047,0.766,39.0,1.0000
45376,2026-01-29T22:58:30Z,BR,Quinto Elemento,Quinto Elemento,trackdone,trackdone,True,False,False,False,...,0.026500,5.0,0.1060,-8.639,0.0,0.0309,113.986,0.335,28.0,1.0000
45377,2026-01-29T23:02:26Z,BR,I'm in Love,Validation Deluxe,trackdone,trackdone,True,False,False,False,...,0.000096,11.0,0.1710,-6.333,0.0,0.0717,82.525,0.630,38.0,1.0000

# Droping duplicates

In [11]:
clean_df = not_na_df.drop_duplicates()

# Export Df

In [ ]:
clean_df.to_csv(PATH_PROCESSED, index=False)